name: Build and Quality Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test:
    name: Build Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm build

      - name: Test build output
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ Build failed - dist directory not found"
            exit 1
          fi
          if [ ! -f "dist/index.html" ]; then
            echo "❌ Build failed - index.html not found"
            exit 1
          fi
          echo "✅ Build output validation passed"

      - name: Check bundle size
        run: |
          BUNDLE_SIZE=$(du -sh dist | cut -f1)
          echo "📦 Bundle size: $BUNDLE_SIZE"

      - name: Analyze bundle contents
        run: |
          echo "📊 Analyzing build output..."
          find dist -name "*.js" -type f -exec du -h {} + | sort -hr | head -5 || echo "No JS files found"
          find dist -name "*.css" -type f -exec du -h {} + | sort -hr | head -5 || echo "No CSS files found"
          
      - name: Check for large assets
        run: |
          echo "🔍 Checking for large assets (>1MB)..."
          find dist -type f -size +1M -exec ls -lh {} + || echo "✅ No large assets found"

  preview-test:
    name: Preview Server Test
    runs-on: ubuntu-latest
    needs: build-test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm build

      - name: Start preview server
        run: pnpm preview &
        env:
          PORT: 4321

      - name: Wait for server and test
        run: |
          echo "Waiting for server to start..."
          sleep 10
          curl -f http://localhost:4321 || (echo "❌ Preview server failed" && exit 1)
          echo "✅ Preview server working correctly"

  accessibility-check:
    name: Accessibility Tests
    runs-on: ubuntu-latest
    needs: build-test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm build

      - name: Start preview server
        run: pnpm preview &
        env:
          PORT: 4321

      - name: Wait for server
        run: |
          echo "Waiting for server to start..."
          sleep 10
          curl -f http://localhost:4321 || exit 1

      - name: Install axe-core CLI
        run: npm install -g @axe-core/cli

      - name: Run accessibility tests
        run: |
          axe http://localhost:4321 --exit || echo "⚠️ Accessibility issues found"
        continue-on-error: true

  performance-check:
    name: Performance Tests  
    runs-on: ubuntu-latest
    needs: build-test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm build

      - name: Analyze bundle
        run: |
          echo "📊 Analyzing build output..."
          find dist -name "*.js" -type f -exec du -h {} + | sort -hr | head -10
          find dist -name "*.css" -type f -exec du -h {} + | sort -hr | head -5
          
      - name: Check for large assets
        run: |
          echo "🔍 Checking for large assets (>1MB)..."
          find dist -type f -size +1M -exec ls -lh {} + || echo "✅ No large assets found"

  link-check:
    name: Link Validation
    runs-on: ubuntu-latest
    needs: build-test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm build

      - name: Start preview server
        run: pnpm preview &
        env:
          PORT: 4321

      - name: Wait for server
        run: |
          echo "Waiting for server to start..."
          sleep 5

      - name: Install link checker
        run: npm install -g broken-link-checker

      - name: Check internal links
        run: |
          blc http://localhost:4321 -r --filter-level 3 || echo "⚠️ Some links may be broken"
        continue-on-error: true 