name: Update Badges

on:
  workflow_run:
    workflows: ["Lint and Test", "Comprehensive Tests", "Build and Deploy"]
    types: [ completed ]
  schedule:
    # Update badges daily at 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  update-badges:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README badges
        run: |
          echo "📊 Badge status updated automatically"
          # Badges are automatically updated by GitHub's API
          # This job serves as a trigger for badge refresh

      - name: Check workflow status
        run: |
          echo "✅ Badge update workflow completed" 